services:
  - type: web
    # plan: free
    name: portfolio-app
    runtime: static
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~20.7.0
    headers:
    - path: /*
      name: X-Frame-Options
      value: sameorigin