services:
  - type: web
    name: portfolio-app
    runtime: static
    branch: dev
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    healthCheckPath: /_health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: ~20.7.0
      - key: VITE_STRAPI_URL
        value: https://portfolio-api-yi9v.onrender.com
    headers:
    - path: /*
      name: X-Frame-Options
      value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html